### PR TITLE
Patched b753c and b420

### PR DESCRIPTION
**Pull request by Zordon1337**

### CODE REVIEW

**Review by Lekuruu — CHANGES_REQUESTED** [review]
I've just tested b753c, and that one should be fine. There are a few things you need to change:

- Please remove the "_patched" from the zip filenames
- Please avoid any subfolders inside the zip file (the game should be in the root folder of the zip file)
- Please remove all files ending with .db and .cfg, and also remove all of the folders inside the game directory

Sorry that this review took so long, I will test b420 in a short moment as well.

**Comment by Lekuruu** [comment]
I've tested the b420 build on Linux, Windows 10 and Windows XP now. It sadly only works on linux somehow. I have no idea why this is the case. I will let you know when I've found a fix.

**Comment by Lekuruu** [comment]
Ok I have found out why this is happening. Turns out some dll files were missing from the folder, which caused windows to terminate the program. It's funny that wine can load it successfully.
There is one problem however. The client doesn't support the new slider format that got added in newer versions, so you can basically only play a *very* small subset of beatmaps properly. Because of that I am not sure if it should be included or not.

**Comment by Zordon1337** [comment]
> Ok I have found out why this is happening. Turns out some dll files were missing from the folder, which caused windows to terminate the program. It's funny that wine can load it successfully. There is one problem however. The client doesn't support the new slider format that got added in newer versions, so you can basically only play a _very_ small subset of beatmaps properly. Because of that I am not sure if it should be included or not.

we can add small note in b420 that sliders are NOT supported and only small amount of maps will work

**Comment by Lekuruu** [comment]
Sure, that would be a way to do it. I will test multiplayer and then merge if no issues are present.

**Comment by Lekuruu** [comment]
I am currently debugging some issues with multiplayer in b753c. Doesn't seem to be the issue of the protocol, but more like an issue with the game. The game tries to access a sprite collection list, which is empty somehow, and then just crashes. Will try to investigate this as best as I can.

**Comment by Lekuruu** [comment]
I've re-patched the client manually and it works now. No idea what happened there.
Here is the new exe: https://cdn.discordapp.com/attachments/1153055598708015124/1193684090554171512/osu.exe

**Review by Lekuruu — APPROVED** [review]

**Pull request merged**
