### PR TITLE
Update readme!

### PR DESCRIPTION
**Pull request by NamOpt**
i completed the new readme and everyone pls help me upload the build on github, i cant using git lfs

### CODE REVIEW

**Comment by Lekuruu** [comment]
We aren't storing builds on GitHub anymore, due to git lfs issues

**Comment by NamOpt** [comment]
ok, how I can create a new rep withour uisng git lfs (buggy suck niga)

**Comment by Lekuruu** [comment]
You can't use git lfs inside forks.

**Comment by kanaarima** [comment]
> ok, how I can create a new rep withour uisng git lfs (buggy suck niga) and I want to help support the osu!titanic project!

Please use coherent language if you want to contribute in any way to titanic.

**Comment by NamOpt** [comment]
Okay, I will using Vietnamese. Will you accept?

**Pull request closed without merging**
